### PR TITLE
Remove catalog folder.

### PR DESCRIPTION
**Pull request by lisamburns**
This is no longer needed for accelerators
the backstage action (now) generates the file “out of thin air”. It doesn’t need a template and will overwrite it
it writes to /catalog-info.yaml , using the name chosen by the user for their app (projectName option in the accelerator) and tags from the accelerator

### CODE REVIEW

**Review by trisberg — APPROVED** [review]
Removed handling of catalog-info in accelerator.yaml

**Comment by kdvolder** [comment]
I should point out that it may still be needed for any folks trying to do the 'getting started' from tap beta 3. So until beat 3 is superseded by the next release, it may be a little premature to remove this today.

Case in point, it breaks the sample workload on my test cluster.

**Comment by trisberg** [comment]
> I should point out that it may still be needed for any folks trying to do the 'getting started' from tap beta 3. So until beta 3 is superseded by the next release, it may be a little premature to remove this today.
> 
> Case in point, it breaks the sample workload on my test cluster.

This is strange, could you elaborate how this breaks your workload? The accelerators that we ship as part of the betas all use tags like `tap-beta3` to avoid any issues if we update the accelerators.

**Comment by kdvolder** [comment]
It doesn't break the workload it just removes it from TAP UI because it no longer has a catalog entry.

**Comment by trisberg** [comment]
Not sure I follow - you push the project generated by the accelerator to your own git repo, so any changes made to the sample wouldn't affect you. The accelerator still points to the `tap-beta3` tag which has the catalog-info file https://github.com/sample-accelerators/tanzu-java-web-app/tree/tap-beta3/catalog

**Comment by kdvolder** [comment]
> Not sure I follow - you push the project generated by the accelerator to your own git repo

Yes, that would the natural flow of things. However... the TAP Beta 3 getting started tutorial doesn't do this, it simply points directly at *this* repo and uses it as a simple boot app. This is pure oportunism to avoid telling users to do all the steps of getting a project from accelerator, unpacking zip, creating a repo somewhere, pushing it there etc.

Naturally you can understand that someone writing a tutorial might want to avoid explaining all those things if their goal was to get a user to get something up as quickly as possible.

Similarly, when I setup our own test cluster with sample workload I also did the same exact thing as I was going through that tutorial step-by-step exactly. I realize I could have gone the extra mile and clone it somewhere else, or create it via accelerator etc. But I didn't really feel like creating 'yet another hello world boot app' in my own personal github account (it is kind of has got a few of those already).

Anyway... to be absolutely clear: Yes, there is a tutorial out there that *points a workload directly to this repo's main branch*. It does not point at a clone or another branch, nor does it really explain how to create one from a clone, or how to create one from an accelerator zip. 

See step 5 here: https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/0.3/tap-0-3/GUID-getting-started.html

```
tanzu apps workload create tanzu-java-web-app \
--git-repo https://github.com/sample-accelerators/tanzu-java-web-app \
--git-branch main \
--type web \
--label app.kubernetes.io/part-of=tanzu-java-web-app \
--yes
```

Note: don't be fooled by the fact that there are screenshots of accelerator right above there. If you read and follow the steps carefully, you will realise that it doesn't actually use the downloaded zip in the tutorial steps (it is just a flyby of accelerator, without actually using it's zip).

Yes, that's a bit confusing, and I have expressed as much to some folks working on the docs, they seemed to agree and will probably change that flow for beta 4 / GA. In the mean time though anyone doing the tutorila may have issues getting the sample workload to show up in TAP UI.

**Comment by trisberg** [comment]
So couldn't they use `--git-tag tap-beta3` instead of the main branch and everything would work as expected. I don't fully understand how a workload shows up in the TAP GUI. Maybe someone that understands the whole workload flow end-to-end can coordinate this.

**Comment by kdvolder** [comment]
> So couldn't they use --git-tag tap-beta3 instead of the main branch and everything would work as expected

They could, but they didn't.

> I don't fully understand how a workload shows up in the TAP GUI

You and me both :-). But my understand is that for beta3... a user needs to create a config file when installing tap GUI, that points to a catalog location in a git repo, that points in turn to a catalog entry in another git repo, that in turn declares some pattern that TAP GUI then uses to find the workload resources in a k8s cluster that it will show to a user as being part of a 'component', provided that the workload k8s resource also are declared in such a way that they match that pattern.  Yeah... it sounds a bit complicated and I'm not sure I remember if I have all the necessary indirections/steps in there.

This complex mechanic is going to change and be simplified for beta4, but I am not one who is really aware of exactly how it will change or how it will work. But I beleave there will no longer be a need to do all these things described above just to have a workload be visible in TAP UI. (So that means it is indeed the right thing to remove this file from the sample).

**Comment by trisberg** [comment]
@kdvolder @lisamburns we just removed the auto-generation of the catalog-info.yaml file in TAP GUI, so I'm going to add this file back here in this sample accelerator

**Pull request merged**
